local AddonName, Addon = ...

local LSM = LibStub("LibSharedMedia-3.0")

function Addon:RegisterLSM()
    --StatusBars
    LSM:Register("statusbar","VXJedi", [[Interface\Addons\VXJediMedia\StatusBars\VXJedi]])
    LSM:Register("statusbar","Kait", [[Interface\Addons\VXJediMedia\StatusBars\Kait.tga]])
    --Sounds
    LSM:Register("sound","|cffA855F701|r", [[Interface\Addons\VXJediMedia\Sounds\01.ogg]])
    LSM:Register("sound","|cffA855F702|r", [[Interface\Addons\VXJediMedia\Sounds\02.ogg]])
    LSM:Register("sound","|cffA855F703|r", [[Interface\Addons\VXJediMedia\Sounds\03.ogg]])
    LSM:Register("sound","|cffA855F704|r", [[Interface\Addons\VXJediMedia\Sounds\04.ogg]])
    LSM:Register("sound","|cffA855F705|r", [[Interface\Addons\VXJediMedia\Sounds\05.ogg]])
    LSM:Register("sound","|cffA855F706|r", [[Interface\Addons\VXJediMedia\Sounds\06.ogg]])
    LSM:Register("sound","|cffA855F707|r", [[Interface\Addons\VXJediMedia\Sounds\07.ogg]])
    LSM:Register("sound","|cffA855F708|r", [[Interface\Addons\VXJediMedia\Sounds\08.ogg]])
    LSM:Register("sound","|cffA855F71|r", [[Interface\Addons\VXJediMedia\Sounds\1.ogg]])
    LSM:Register("sound","|cffA855F710|r", [[Interface\Addons\VXJediMedia\Sounds\10.ogg]])
    LSM:Register("sound","|cffA855F72|r", [[Interface\Addons\VXJediMedia\Sounds\2.ogg]])
    LSM:Register("sound","|cffA855F73|r", [[Interface\Addons\VXJediMedia\Sounds\3.ogg]])
    LSM:Register("sound","|cffA855F74|r", [[Interface\Addons\VXJediMedia\Sounds\4.ogg]])
    LSM:Register("sound","|cffA855F75|r", [[Interface\Addons\VXJediMedia\Sounds\5.ogg]])
    LSM:Register("sound","|cffA855F76|r", [[Interface\Addons\VXJediMedia\Sounds\6.ogg]])
    LSM:Register("sound","|cffA855F77|r", [[Interface\Addons\VXJediMedia\Sounds\7.ogg]])
    LSM:Register("sound","|cffA855F78|r", [[Interface\Addons\VXJediMedia\Sounds\8.ogg]])
    LSM:Register("sound","|cffA855F79|r", [[Interface\Addons\VXJediMedia\Sounds\9.ogg]])
    LSM:Register("sound","|cffA855F7Absorb|r", [[Interface\Addons\VXJediMedia\Sounds\Absorb.ogg]])
    LSM:Register("sound","|cffA855F7Absorbs|r", [[Interface\Addons\VXJediMedia\Sounds\Absorbs.ogg]])
    LSM:Register("sound","|cffA855F7Add Frontal|r", [[Interface\Addons\VXJediMedia\Sounds\Add Frontal.ogg]])
    LSM:Register("sound","|cffA855F7Add|r", [[Interface\Addons\VXJediMedia\Sounds\Add.ogg]])
    LSM:Register("sound","|cffA855F7Adds Buffed|r", [[Interface\Addons\VXJediMedia\Sounds\Adds Buffed.ogg]])
    LSM:Register("sound","|cffA855F7Adds|r", [[Interface\Addons\VXJediMedia\Sounds\Adds.ogg]])
    LSM:Register("sound","|cffA855F7Affix Complete|r", [[Interface\Addons\VXJediMedia\Sounds\Affix Complete.ogg]])
    LSM:Register("sound","|cffA855F7Affix|r", [[Interface\Addons\VXJediMedia\Sounds\Affix.ogg]])
    LSM:Register("sound","|cffA855F7Aim Charge|r", [[Interface\Addons\VXJediMedia\Sounds\Aim Charge.ogg]])
    LSM:Register("sound","|cffA855F7AoE|r", [[Interface\Addons\VXJediMedia\Sounds\AoE.ogg]])
    LSM:Register("sound","|cffA855F7Aoe And Dance|r", [[Interface\Addons\VXJediMedia\Sounds\Aoe And Dance.ogg]])
    LSM:Register("sound","|cffA855F7Assist|r", [[Interface\Addons\VXJediMedia\Sounds\Assist.ogg]])
    LSM:Register("sound","|cffA855F7Avoid Tank|r", [[Interface\Addons\VXJediMedia\Sounds\Avoid Tank.ogg]])
    LSM:Register("sound","|cffA855F7Avoid|r", [[Interface\Addons\VXJediMedia\Sounds\Avoid.ogg]])
    LSM:Register("sound","|cffA855F7Back|r", [[Interface\Addons\VXJediMedia\Sounds\Back.ogg]])
    LSM:Register("sound","|cffA855F7Backup|r", [[Interface\Addons\VXJediMedia\Sounds\Backup.ogg]])
    LSM:Register("sound","|cffA855F7Bait|r", [[Interface\Addons\VXJediMedia\Sounds\Bait.ogg]])
    LSM:Register("sound","|cffA855F7Balls Charging|r", [[Interface\Addons\VXJediMedia\Sounds\Balls Charging.ogg]])
    LSM:Register("sound","|cffA855F7Bark|r", [[Interface\Addons\VXJediMedia\Sounds\Bark.ogg]])
    LSM:Register("sound","|cffA855F7Beam|r", [[Interface\Addons\VXJediMedia\Sounds\Beam.ogg]])
    LSM:Register("sound","|cffA855F7Beams|r", [[Interface\Addons\VXJediMedia\Sounds\Beams.ogg]])
    LSM:Register("sound","|cffA855F7Blade|r", [[Interface\Addons\VXJediMedia\Sounds\Blade.ogg]])
    LSM:Register("sound","|cffA855F7Blades|r", [[Interface\Addons\VXJediMedia\Sounds\Blades.ogg]])
    LSM:Register("sound","|cffA855F7Blast|r", [[Interface\Addons\VXJediMedia\Sounds\Blast.ogg]])
    LSM:Register("sound","|cffA855F7Bleed|r", [[Interface\Addons\VXJediMedia\Sounds\Bleed.ogg]])
    LSM:Register("sound","|cffA855F7Blood|r", [[Interface\Addons\VXJediMedia\Sounds\Blood.ogg]])
    LSM:Register("sound","|cffA855F7Bloodlust|r", [[Interface\Addons\VXJediMedia\Sounds\Bloodlust.ogg]])
    LSM:Register("sound","|cffA855F7Blue|r", [[Interface\Addons\VXJediMedia\Sounds\Blue.ogg]])
    LSM:Register("sound","|cffA855F7BoP|r", [[Interface\Addons\VXJediMedia\Sounds\BoP.ogg]])
    LSM:Register("sound","|cffA855F7Bombs Incoming|r", [[Interface\Addons\VXJediMedia\Sounds\Bombs Incoming.ogg]])
    LSM:Register("sound","|cffA855F7Bombs|r", [[Interface\Addons\VXJediMedia\Sounds\Bombs.ogg]])
    LSM:Register("sound","|cffA855F7Boss Buffed|r", [[Interface\Addons\VXJediMedia\Sounds\Boss Buffed.ogg]])
    LSM:Register("sound","|cffA855F7Boss Position|r", [[Interface\Addons\VXJediMedia\Sounds\Boss Position.ogg]])
    LSM:Register("sound","|cffA855F7Boss Shielded|r", [[Interface\Addons\VXJediMedia\Sounds\Boss Shielded.ogg]])
    LSM:Register("sound","|cffA855F7Boss|r", [[Interface\Addons\VXJediMedia\Sounds\Boss.ogg]])
    LSM:Register("sound","|cffA855F7Box Incoming|r", [[Interface\Addons\VXJediMedia\Sounds\Box Incoming.ogg]])
    LSM:Register("sound","|cffA855F7Break|r", [[Interface\Addons\VXJediMedia\Sounds\Break.ogg]])
    LSM:Register("sound","|cffA855F7Buff|r", [[Interface\Addons\VXJediMedia\Sounds\Buff.ogg]])
    LSM:Register("sound","|cffA855F7Buffed|r", [[Interface\Addons\VXJediMedia\Sounds\Buffed.ogg]])
    LSM:Register("sound","|cffA855F7Buffing Add|r", [[Interface\Addons\VXJediMedia\Sounds\Buffing Add.ogg]])
    LSM:Register("sound","|cffA855F7Bullet|r", [[Interface\Addons\VXJediMedia\Sounds\Bullet.ogg]])
    LSM:Register("sound","|cffA855F7CC|r", [[Interface\Addons\VXJediMedia\Sounds\CC.ogg]])
    LSM:Register("sound","|cffA855F7CD|r", [[Interface\Addons\VXJediMedia\Sounds\CD.ogg]])
    LSM:Register("sound","|cffA855F7Cage|r", [[Interface\Addons\VXJediMedia\Sounds\Cage.ogg]])
    LSM:Register("sound","|cffA855F7Center|r", [[Interface\Addons\VXJediMedia\Sounds\Center.ogg]])
    LSM:Register("sound","|cffA855F7Chain|r", [[Interface\Addons\VXJediMedia\Sounds\Chain.ogg]])
    LSM:Register("sound","|cffA855F7Charge|r", [[Interface\Addons\VXJediMedia\Sounds\Charge.ogg]])
    LSM:Register("sound","|cffA855F7Charges Incoming|r", [[Interface\Addons\VXJediMedia\Sounds\Charges Incoming.ogg]])
    LSM:Register("sound","|cffA855F7Clear|r", [[Interface\Addons\VXJediMedia\Sounds\Clear.ogg]])
    LSM:Register("sound","|cffA855F7Coin Magnet|r", [[Interface\Addons\VXJediMedia\Sounds\Coin Magnet.ogg]])
    LSM:Register("sound","|cffA855F7Coin Pull|r", [[Interface\Addons\VXJediMedia\Sounds\Coin Pull.ogg]])
    LSM:Register("sound","|cffA855F7Collect|r", [[Interface\Addons\VXJediMedia\Sounds\Collect.ogg]])
    LSM:Register("sound","|cffA855F7Cross|r", [[Interface\Addons\VXJediMedia\Sounds\Cross.ogg]])
    LSM:Register("sound","|cffA855F7Curse|r", [[Interface\Addons\VXJediMedia\Sounds\Curse.ogg]])
    LSM:Register("sound","|cffA855F7Dance|r", [[Interface\Addons\VXJediMedia\Sounds\Dance.ogg]])
    LSM:Register("sound","|cffA855F7Debuff|r", [[Interface\Addons\VXJediMedia\Sounds\Debuff.ogg]])
    LSM:Register("sound","|cffA855F7Debuffs|r", [[Interface\Addons\VXJediMedia\Sounds\Debuffs.ogg]])
    LSM:Register("sound","|cffA855F7Decurse|r", [[Interface\Addons\VXJediMedia\Sounds\Decurse.ogg]])
    LSM:Register("sound","|cffA855F7Defensive|r", [[Interface\Addons\VXJediMedia\Sounds\Defensive.ogg]])
    LSM:Register("sound","|cffA855F7Disease|r", [[Interface\Addons\VXJediMedia\Sounds\Disease.ogg]])
    LSM:Register("sound","|cffA855F7Dispel Tank|r", [[Interface\Addons\VXJediMedia\Sounds\Dispel Tank.ogg]])
    LSM:Register("sound","|cffA855F7Dispell|r", [[Interface\Addons\VXJediMedia\Sounds\Dispell.ogg]])
    LSM:Register("sound","|cffA855F7Dmg Amp|r", [[Interface\Addons\VXJediMedia\Sounds\Dmg Amp.ogg]])
    LSM:Register("sound","|cffA855F7Dodge Together|r", [[Interface\Addons\VXJediMedia\Sounds\Dodge Together.ogg]])
    LSM:Register("sound","|cffA855F7Dodge|r", [[Interface\Addons\VXJediMedia\Sounds\Dodge.ogg]])
    LSM:Register("sound","|cffA855F7Dont Move|r", [[Interface\Addons\VXJediMedia\Sounds\Dont Move.ogg]])
    LSM:Register("sound","|cffA855F7Dot|r", [[Interface\Addons\VXJediMedia\Sounds\Dot.ogg]])
    LSM:Register("sound","|cffA855F7Drop|r", [[Interface\Addons\VXJediMedia\Sounds\Drop.ogg]])
    LSM:Register("sound","|cffA855F7Duck|r", [[Interface\Addons\VXJediMedia\Sounds\Duck.ogg]])
    LSM:Register("sound","|cffA855F7Enter|r", [[Interface\Addons\VXJediMedia\Sounds\Enter.ogg]])
    LSM:Register("sound","|cffA855F7Escort|r", [[Interface\Addons\VXJediMedia\Sounds\Escort.ogg]])
    LSM:Register("sound","|cffA855F7Exit|r", [[Interface\Addons\VXJediMedia\Sounds\Exit.ogg]])
    LSM:Register("sound","|cffA855F7Fear|r", [[Interface\Addons\VXJediMedia\Sounds\Fear.ogg]])
    LSM:Register("sound","|cffA855F7Feet|r", [[Interface\Addons\VXJediMedia\Sounds\Feet.ogg]])
    LSM:Register("sound","|cffA855F7Find Safespot|r", [[Interface\Addons\VXJediMedia\Sounds\Find Safespot.ogg]])
    LSM:Register("sound","|cffA855F7Fixate Incoming|r", [[Interface\Addons\VXJediMedia\Sounds\Fixate Incoming.ogg]])
    LSM:Register("sound","|cffA855F7Fixate|r", [[Interface\Addons\VXJediMedia\Sounds\Fixate.ogg]])
    LSM:Register("sound","|cffA855F7Flipper|r", [[Interface\Addons\VXJediMedia\Sounds\Flipper.ogg]])
    LSM:Register("sound","|cffA855F7Focus|r", [[Interface\Addons\VXJediMedia\Sounds\Focus.ogg]])
    LSM:Register("sound","|cffA855F7Front|r", [[Interface\Addons\VXJediMedia\Sounds\Front.ogg]])
    LSM:Register("sound","|cffA855F7Frontal|r", [[Interface\Addons\VXJediMedia\Sounds\Frontal.ogg]])
    LSM:Register("sound","|cffA855F7Gate|r", [[Interface\Addons\VXJediMedia\Sounds\Gate.ogg]])
    LSM:Register("sound","|cffA855F7Gather|r", [[Interface\Addons\VXJediMedia\Sounds\Gather.ogg]])
    LSM:Register("sound","|cffA855F7Get Dispelled|r", [[Interface\Addons\VXJediMedia\Sounds\Get Dispelled.ogg]])
    LSM:Register("sound","|cffA855F7Green|r", [[Interface\Addons\VXJediMedia\Sounds\Green.ogg]])
    LSM:Register("sound","|cffA855F7Headlock Stun|r", [[Interface\Addons\VXJediMedia\Sounds\Headlock Stun.ogg]])
    LSM:Register("sound","|cffA855F7Healcd|r", [[Interface\Addons\VXJediMedia\Sounds\Healcd.ogg]])
    LSM:Register("sound","|cffA855F7Hide|r", [[Interface\Addons\VXJediMedia\Sounds\Hide.ogg]])
    LSM:Register("sound","|cffA855F7High Energy|r", [[Interface\Addons\VXJediMedia\Sounds\High Energy.ogg]])
    LSM:Register("sound","|cffA855F7High Stacks|r", [[Interface\Addons\VXJediMedia\Sounds\High Stacks.ogg]])
    LSM:Register("sound","|cffA855F7Hooks Incoming|r", [[Interface\Addons\VXJediMedia\Sounds\Hooks Incoming.ogg]])
    LSM:Register("sound","|cffA855F7Immunity|r", [[Interface\Addons\VXJediMedia\Sounds\Immunity.ogg]])
    LSM:Register("sound","|cffA855F7In|r", [[Interface\Addons\VXJediMedia\Sounds\In.ogg]])
    LSM:Register("sound","|cffA855F7Info|r", [[Interface\Addons\VXJediMedia\Sounds\Info.ogg]])
    LSM:Register("sound","|cffA855F7Innervate|r", [[Interface\Addons\VXJediMedia\Sounds\Innervate.ogg]])
    LSM:Register("sound","|cffA855F7Intermission Over|r", [[Interface\Addons\VXJediMedia\Sounds\Intermission Over.ogg]])
    LSM:Register("sound","|cffA855F7Intermission|r", [[Interface\Addons\VXJediMedia\Sounds\Intermission.ogg]])
    LSM:Register("sound","|cffA855F7Interrupt|r", [[Interface\Addons\VXJediMedia\Sounds\Interrupt.ogg]])
    LSM:Register("sound","|cffA855F7Invisibility|r", [[Interface\Addons\VXJediMedia\Sounds\Invisibility.ogg]])
    LSM:Register("sound","|cffA855F7Jump|r", [[Interface\Addons\VXJediMedia\Sounds\Jump.ogg]])
    LSM:Register("sound","|cffA855F7Kick|r", [[Interface\Addons\VXJediMedia\Sounds\Kick.ogg]])
    LSM:Register("sound","|cffA855F7Knock|r", [[Interface\Addons\VXJediMedia\Sounds\Knock.ogg]])
    LSM:Register("sound","|cffA855F7Knockback|r", [[Interface\Addons\VXJediMedia\Sounds\Knockback.ogg]])
    LSM:Register("sound","|cffA855F7Leap|r", [[Interface\Addons\VXJediMedia\Sounds\Leap.ogg]])
    LSM:Register("sound","|cffA855F7Left|r", [[Interface\Addons\VXJediMedia\Sounds\Left.ogg]])
    LSM:Register("sound","|cffA855F7Linked|r", [[Interface\Addons\VXJediMedia\Sounds\Linked.ogg]])
    LSM:Register("sound","|cffA855F7Links Incoming|r", [[Interface\Addons\VXJediMedia\Sounds\Links Incoming.ogg]])
    LSM:Register("sound","|cffA855F7LoS|r", [[Interface\Addons\VXJediMedia\Sounds\LoS.ogg]])
    LSM:Register("sound","|cffA855F7Look Away|r", [[Interface\Addons\VXJediMedia\Sounds\Look Away.ogg]])
    LSM:Register("sound","|cffA855F7MC|r", [[Interface\Addons\VXJediMedia\Sounds\MC.ogg]])
    LSM:Register("sound","|cffA855F7Magic|r", [[Interface\Addons\VXJediMedia\Sounds\Magic.ogg]])
    LSM:Register("sound","|cffA855F7Mail|r", [[Interface\Addons\VXJediMedia\Sounds\Mail.ogg]])
    LSM:Register("sound","|cffA855F7Main|r", [[Interface\Addons\VXJediMedia\Sounds\Main.ogg]])
    LSM:Register("sound","|cffA855F7Maul|r", [[Interface\Addons\VXJediMedia\Sounds\Maul.ogg]])
    LSM:Register("sound","|cffA855F7Max Dmg Amp|r", [[Interface\Addons\VXJediMedia\Sounds\Max Dmg Amp.ogg]])
    LSM:Register("sound","|cffA855F7Melee|r", [[Interface\Addons\VXJediMedia\Sounds\Melee.ogg]])
    LSM:Register("sound","|cffA855F7Mines|r", [[Interface\Addons\VXJediMedia\Sounds\Mines.ogg]])
    LSM:Register("sound","|cffA855F7Miniboss Buffed|r", [[Interface\Addons\VXJediMedia\Sounds\Miniboss Buffed.ogg]])
    LSM:Register("sound","|cffA855F7Missile|r", [[Interface\Addons\VXJediMedia\Sounds\Missile.ogg]])
    LSM:Register("sound","|cffA855F7Move|r", [[Interface\Addons\VXJediMedia\Sounds\Move.ogg]])
    LSM:Register("sound","|cffA855F7New Add|r", [[Interface\Addons\VXJediMedia\Sounds\New Add.ogg]])
    LSM:Register("sound","|cffA855F7Next|r", [[Interface\Addons\VXJediMedia\Sounds\Next.ogg]])
    LSM:Register("sound","|cffA855F7Nuke|r", [[Interface\Addons\VXJediMedia\Sounds\Nuke.ogg]])
    LSM:Register("sound","|cffA855F7OnYou|r", [[Interface\Addons\VXJediMedia\Sounds\OnYou.ogg]])
    LSM:Register("sound","|cffA855F7Orange|r", [[Interface\Addons\VXJediMedia\Sounds\Orange.ogg]])
    LSM:Register("sound","|cffA855F7Orb|r", [[Interface\Addons\VXJediMedia\Sounds\Orb.ogg]])
    LSM:Register("sound","|cffA855F7Orbs|r", [[Interface\Addons\VXJediMedia\Sounds\Orbs.ogg]])
    LSM:Register("sound","|cffA855F7Out|r", [[Interface\Addons\VXJediMedia\Sounds\Out.ogg]])
    LSM:Register("sound","|cffA855F7Overlap|r", [[Interface\Addons\VXJediMedia\Sounds\Overlap.ogg]])
    LSM:Register("sound","|cffA855F7PI|r", [[Interface\Addons\VXJediMedia\Sounds\PI.ogg]])
    LSM:Register("sound","|cffA855F7PS|r", [[Interface\Addons\VXJediMedia\Sounds\PS.ogg]])
    LSM:Register("sound","|cffA855F7Phase2|r", [[Interface\Addons\VXJediMedia\Sounds\Phase2.ogg]])
    LSM:Register("sound","|cffA855F7Phase3|r", [[Interface\Addons\VXJediMedia\Sounds\Phase3.ogg]])
    LSM:Register("sound","|cffA855F7Phasing|r", [[Interface\Addons\VXJediMedia\Sounds\Phasing.ogg]])
    LSM:Register("sound","|cffA855F7Physical|r", [[Interface\Addons\VXJediMedia\Sounds\Physical.ogg]])
    LSM:Register("sound","|cffA855F7Pickaxe|r", [[Interface\Addons\VXJediMedia\Sounds\Pickaxe.ogg]])
    LSM:Register("sound","|cffA855F7Poison|r", [[Interface\Addons\VXJediMedia\Sounds\Poison.ogg]])
    LSM:Register("sound","|cffA855F7Pools|r", [[Interface\Addons\VXJediMedia\Sounds\Pools.ogg]])
    LSM:Register("sound","|cffA855F7Positive|r", [[Interface\Addons\VXJediMedia\Sounds\Positive.ogg]])
    LSM:Register("sound","|cffA855F7Pots|r", [[Interface\Addons\VXJediMedia\Sounds\Pots.ogg]])
    LSM:Register("sound","|cffA855F7Pre-Move Inc|r", [[Interface\Addons\VXJediMedia\Sounds\Pre-Move Inc.ogg]])
    LSM:Register("sound","|cffA855F7Pre-Move|r", [[Interface\Addons\VXJediMedia\Sounds\Pre-Move.ogg]])
    LSM:Register("sound","|cffA855F7Pre-Spread|r", [[Interface\Addons\VXJediMedia\Sounds\Pre-Spread.ogg]])
    LSM:Register("sound","|cffA855F7Pull|r", [[Interface\Addons\VXJediMedia\Sounds\Pull.ogg]])
    LSM:Register("sound","|cffA855F7Purple|r", [[Interface\Addons\VXJediMedia\Sounds\Purple.ogg]])
    LSM:Register("sound","|cffA855F7Push|r", [[Interface\Addons\VXJediMedia\Sounds\Push.ogg]])
    LSM:Register("sound","|cffA855F7PvP Incoming|r", [[Interface\Addons\VXJediMedia\Sounds\PvP Incoming.ogg]])
    LSM:Register("sound","|cffA855F7Range|r", [[Interface\Addons\VXJediMedia\Sounds\Range.ogg]])
    LSM:Register("sound","|cffA855F7Ready|r", [[Interface\Addons\VXJediMedia\Sounds\Ready.ogg]])
    LSM:Register("sound","|cffA855F7Red|r", [[Interface\Addons\VXJediMedia\Sounds\Red.ogg]])
    LSM:Register("sound","|cffA855F7Reflect|r", [[Interface\Addons\VXJediMedia\Sounds\Reflect.ogg]])
    LSM:Register("sound","|cffA855F7Remove Plating|r", [[Interface\Addons\VXJediMedia\Sounds\Remove Plating.ogg]])
    LSM:Register("sound","|cffA855F7Ricochet|r", [[Interface\Addons\VXJediMedia\Sounds\Ricochet.ogg]])
    LSM:Register("sound","|cffA855F7Right|r", [[Interface\Addons\VXJediMedia\Sounds\Right.ogg]])
    LSM:Register("sound","|cffA855F7Ring|r", [[Interface\Addons\VXJediMedia\Sounds\Ring.ogg]])
    LSM:Register("sound","|cffA855F7Root|r", [[Interface\Addons\VXJediMedia\Sounds\Root.ogg]])
    LSM:Register("sound","|cffA855F7Run out|r", [[Interface\Addons\VXJediMedia\Sounds\Run out.ogg]])
    LSM:Register("sound","|cffA855F7Sac|r", [[Interface\Addons\VXJediMedia\Sounds\Sac.ogg]])
    LSM:Register("sound","|cffA855F7Sawblade Incoming|r", [[Interface\Addons\VXJediMedia\Sounds\Sawblade Incoming.ogg]])
    LSM:Register("sound","|cffA855F7Seed|r", [[Interface\Addons\VXJediMedia\Sounds\Seed.ogg]])
    LSM:Register("sound","|cffA855F7Selfcd|r", [[Interface\Addons\VXJediMedia\Sounds\Selfcd.ogg]])
    LSM:Register("sound","|cffA855F7Sentry|r", [[Interface\Addons\VXJediMedia\Sounds\Sentry.ogg]])
    LSM:Register("sound","|cffA855F7Shield|r", [[Interface\Addons\VXJediMedia\Sounds\Shield.ogg]])
    LSM:Register("sound","|cffA855F7Side|r", [[Interface\Addons\VXJediMedia\Sounds\Side.ogg]])
    LSM:Register("sound","|cffA855F7Smash|r", [[Interface\Addons\VXJediMedia\Sounds\Smash.ogg]])
    LSM:Register("sound","|cffA855F7Smashing|r", [[Interface\Addons\VXJediMedia\Sounds\Smashing.ogg]])
    LSM:Register("sound","|cffA855F7Soak|r", [[Interface\Addons\VXJediMedia\Sounds\Soak.ogg]])
    LSM:Register("sound","|cffA855F7Soaks|r", [[Interface\Addons\VXJediMedia\Sounds\Soaks.ogg]])
    LSM:Register("sound","|cffA855F7Soon|r", [[Interface\Addons\VXJediMedia\Sounds\Soon.ogg]])
    LSM:Register("sound","|cffA855F7Sparks|r", [[Interface\Addons\VXJediMedia\Sounds\Sparks.ogg]])
    LSM:Register("sound","|cffA855F7Spawn|r", [[Interface\Addons\VXJediMedia\Sounds\Spawn.ogg]])
    LSM:Register("sound","|cffA855F7Spellsteal|r", [[Interface\Addons\VXJediMedia\Sounds\Spellsteal.ogg]])
    LSM:Register("sound","|cffA855F7Spikes|r", [[Interface\Addons\VXJediMedia\Sounds\Spikes.ogg]])
    LSM:Register("sound","|cffA855F7Split|r", [[Interface\Addons\VXJediMedia\Sounds\Split.ogg]])
    LSM:Register("sound","|cffA855F7Spread|r", [[Interface\Addons\VXJediMedia\Sounds\Spread.ogg]])
    LSM:Register("sound","|cffA855F7Stack|r", [[Interface\Addons\VXJediMedia\Sounds\Stack.ogg]])
    LSM:Register("sound","|cffA855F7Statues|r", [[Interface\Addons\VXJediMedia\Sounds\Statues.ogg]])
    LSM:Register("sound","|cffA855F7Stop Casting|r", [[Interface\Addons\VXJediMedia\Sounds\Stop Casting.ogg]])
    LSM:Register("sound","|cffA855F7Stop|r", [[Interface\Addons\VXJediMedia\Sounds\Stop.ogg]])
    LSM:Register("sound","|cffA855F7Stopcast|r", [[Interface\Addons\VXJediMedia\Sounds\Stopcast.ogg]])
    LSM:Register("sound","|cffA855F7Stun|r", [[Interface\Addons\VXJediMedia\Sounds\Stun.ogg]])
    LSM:Register("sound","|cffA855F7Stunned|r", [[Interface\Addons\VXJediMedia\Sounds\Stunned.ogg]])
    LSM:Register("sound","|cffA855F7Successful|r", [[Interface\Addons\VXJediMedia\Sounds\Successful.ogg]])
    LSM:Register("sound","|cffA855F7Swap|r", [[Interface\Addons\VXJediMedia\Sounds\Swap.ogg]])
    LSM:Register("sound","|cffA855F7Switch|r", [[Interface\Addons\VXJediMedia\Sounds\Switch.ogg]])
    LSM:Register("sound","|cffA855F7Tank-Frontal|r", [[Interface\Addons\VXJediMedia\Sounds\Tank-Frontal.ogg]])
    LSM:Register("sound","|cffA855F7Targeted|r", [[Interface\Addons\VXJediMedia\Sounds\Targeted.ogg]])
    LSM:Register("sound","|cffA855F7Taunt|r", [[Interface\Addons\VXJediMedia\Sounds\Taunt.ogg]])
    LSM:Register("sound","|cffA855F7Throw|r", [[Interface\Addons\VXJediMedia\Sounds\Throw.ogg]])
    LSM:Register("sound","|cffA855F7Thunder|r", [[Interface\Addons\VXJediMedia\Sounds\Thunder.ogg]])
    LSM:Register("sound","|cffA855F7Tornadoes|r", [[Interface\Addons\VXJediMedia\Sounds\Tornadoes.ogg]])
    LSM:Register("sound","|cffA855F7Totem|r", [[Interface\Addons\VXJediMedia\Sounds\Totem.ogg]])
    LSM:Register("sound","|cffA855F7Transition|r", [[Interface\Addons\VXJediMedia\Sounds\Transition.ogg]])
    LSM:Register("sound","|cffA855F7Trap|r", [[Interface\Addons\VXJediMedia\Sounds\Trap.ogg]])
    LSM:Register("sound","|cffA855F7Turn|r", [[Interface\Addons\VXJediMedia\Sounds\Turn.ogg]])
    LSM:Register("sound","|cffA855F7Uppercut|r", [[Interface\Addons\VXJediMedia\Sounds\Uppercut.ogg]])
    LSM:Register("sound","|cffA855F7Wave|r", [[Interface\Addons\VXJediMedia\Sounds\Wave.ogg]])
    LSM:Register("sound","|cffA855F7Winds|r", [[Interface\Addons\VXJediMedia\Sounds\Winds.ogg]])
    LSM:Register("sound","|cffA855F7Yellow|r", [[Interface\Addons\VXJediMedia\Sounds\Yellow.ogg]])
    LSM:Register("sound","|cffA855F7Zone|r", [[Interface\Addons\VXJediMedia\Sounds\Zone.ogg]])
    --Fonts
    LSM:Register("font","Expressway", [[Interface\Addons\VXJediMedia\Fonts\Expressway.TTF]])
end

Addon:RegisterLSM()

-- Keybinding labels (shown in Blizzard Keybindings UI)
_G.BINDING_HEADER_VXJEDIMEDIA = "|cffA855F7VXJedi|r|cffffffffMedia|r"
_G.BINDING_NAME_VXJEDIMEDIA_TOGGLEBARS = "Toggle ElvUI Action Bars (1, 4, 5, 6)"
